export const PET_WINDOW_WIDTH = 360
export const PET_WINDOW_HEIGHT = 420

export const BUBBLE_WINDOW_WIDTH = 360
export const BUBBLE_WINDOW_HEIGHT = 420

export const ACTION_DROPDOWN_WINDOW_WIDTH = 560
export const ACTION_DROPDOWN_WINDOW_HEIGHT = 680

export const CONTEXT_MENU_WINDOW_WIDTH = 410
export const CONTEXT_MENU_WINDOW_HEIGHT = 760

export const CHAT_WINDOW_WIDTH = 900
export const CHAT_WINDOW_HEIGHT = 820

export const SETTINGS_WINDOW_WIDTH = 760
export const SETTINGS_WINDOW_HEIGHT = 780
